### ISSUE TITLE
A thought on `VaporExample.Config.get_…/1`

### ISSUE THREAD

**Issue by gausby** [keathley/vapor#10]
The calls of this form:
```elixir
VaporExample.Config.get_int("config_key")
```
Wouldn't it be more extensible, and cleaner to say:
```elixir
VaporExample.Config.get("config_key", as: :int)
```
That way one could make their own data coercers that coerced the value into something that makes sense for their application. Just a thought.

**Comment by keathley** [comment]
In my head I had assumed that users could use whichever coercion function they needed for any given key. So

```elixir
Config.get_int("key")
Config.get_string("key")
Config.get_bool("key")
```

Would all be valid uses. That said I think that passing the "coercion method" as an argument could be useful and could theoretically be extended to allow users to pass in functions if they needed custom coercion methods like so:

```elixir
Config.get("key", as: fn (value) -> my_custom_coercion(value) end)
```

**Comment by keathley** [comment]
I ended up going with this design. Thanks for the suggestion :+1:
